on: [pull_request]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A test
    steps:
      - name: Hello world
        id: hello
        uses: useparcel/wait-for-deployments-action@test
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
